on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'SARA'
        run: pwd
      - uses: actions/checkout@v3
      - name: 'Show'
        run: ls
      - name: 'login'
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}  
      - name: 'build' 
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/task2 .
      - name: 'push'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/task2

  



  
